Revert "Верстка трех страниц"
htmlacademy-adaptive/2198955-cat-energy-27 pull request #2
Opened 2022-12-01 13:55 UTC by danikoff

This reverts commit 0330075a64ca138a634c27950f5b7de9c7adff2d.

2022-12-02 11:57 UTC, babtshe requested changes

2022-12-02 11:57 UTC, babtshe commented on Readme.md
> +* Наставник: `Александр Бабченко`.
ссылку на профиль неплохо было бы добавить по аналогии со строкой выше

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +      </div>
логотип вполне можно сделать отдельным БЭМ-блоком, ссылка ведёт на главную

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +            <li class="main-nav__item"><a href="#">Каталог продукции</a>
страница не должна ссылаться сама на себя, href тут можно убрать, а в остальных пунктах меню ссылки стоит проставить.

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +      <h2 class="catalog__titel">каталог-продуции</h2>
- На странице не может быть h2 без h1
- Нет пользы от дублирования заголовка дважды в скрытом и явном виде
- обрати внимание на имя для элемента блока

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +          </div>
откуда тут логотип?

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +            <h3 class="catalog__item-titel">Cat Energy PRO 500 г</h3>
здесь и далее опечатка в названии элемента

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +                <span>500 г</span>
здесь лучше будет использовать список определений

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +          <button class="button-item" type="button">заказать</button>
кнопку покупки безопаснее делать ссылкой, тогда пользователь сможет купить товар, даже если скрипты сломались/выключены

2022-12-02 11:57 UTC, babtshe commented on source/catalog.html
> +        Санкт-Петербург</p>
для адреса есть специальный тег

2022-12-02 11:57 UTC, babtshe commented on source/form.html
> +      <fieldset class="">
зачем тут класс, если он пустой?

2022-12-02 11:57 UTC, babtshe commented on source/form.html
> +        <input class="section-form__input-form" name="name" value="барсик" type="text">
если поле обязательное, хорошо будет добавить соответствующий атрибут
вместо value будет правильно использовать placeholder

2022-12-02 11:57 UTC, babtshe commented on source/form.html
> +        <input class="section-form__input-form" name="weight" value="7" type="text">
обрати внимание на тип поля здесь и далее

2022-12-02 11:57 UTC, babtshe commented on source/form.html
> +              <span class="section-form__control-mark"></span>
для чего этот элемент?

2022-12-02 11:57 UTC, babtshe commented on source/form.html
> +              <input class="section-form__controls-input visually-hidden" type="radio" name="name of prog" checked
стоит избегать пробелов и сокращений в названиях атрибутов, в данном случае имя вполне можно заменить одним словом без потери полезного действия

2022-12-02 11:57 UTC, babtshe commented on source/form.html
> +          <input type="text" value="Расскажите обо всех повадках кота">
тут нужен многострочный инпут для текста

2022-12-02 11:57 UTC, babtshe commented on source/form.html
> +              <input class="section-form__controls-input visually-hidden" type="checkbox" name="сахарозаменитель"
для чекбоксов будет полезно задать одинаковое имя, но разные значения. Тогда собранные данные поедут на сервер в виде удобного массива

2022-12-02 11:57 UTC, babtshe commented on source/index.html
> +      <img class="main__promo-bg promo-bg" src="img/htmlacademy.svg" alt="">
ссылки на картинки хорошо либо не ставить совсем, либо делать сразу правильными. Чистить заглушки потом - двойная работа

2022-12-03 13:13 UTC, danikoff commented on source/form.html
> +              <span class="section-form__control-mark"></span>
Речь если об этом  <span class="section-form__control-mark"></span> , для стилизации радио , на него повесить стили для радио кнопки

2022-12-03 13:13 UTC, danikoff commented on source/form.html
> +              <span class="section-form__control-mark"></span>
span class="section-form__control-mark"></spa

2022-12-03 13:42 UTC, danikoff commented on source/form.html
> +              <input class="section-form__controls-input visually-hidden" type="checkbox" name="сахарозаменитель"
Не понял про разные значения)

2022-12-06 07:39 UTC, babtshe commented on source/form.html
> +              <span class="section-form__control-mark"></span>
это псевдоэлементами делается

2022-12-06 07:39 UTC, babtshe commented on source/form.html
> +              <input class="section-form__controls-input visually-hidden" type="checkbox" name="сахарозаменитель"
value же

2022-12-06 07:50 UTC, babtshe requested changes

2022-12-06 07:50 UTC, babtshe commented on source/catalog.html
> +        <a class="main-header__logo2" href="index.html"><img src="../source/img/index/logo-txt.svg" alt="логотип"></a>
ссылок на source нигде в проекте не должно быть, так как у собранной версии нет доступа к исходникам:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/30229773/205850773-fa4b8d3f-10bc-48c7-9967-00d402d20e49.png">

2022-12-06 07:50 UTC, babtshe commented on source/catalog.html
> +            <li class="main-nav__item"><a href="../source/index.html">Главная</a>
❗️

2022-12-06 07:50 UTC, babtshe commented on source/catalog.html
>      <section class="catalog">
Оба этих элемента превратятся в отдельные БЭМ-блоки, какая от этого польза?

2022-12-06 07:50 UTC, babtshe commented on source/catalog.html
> +      <h1 class="catalog__titel">каталог продуции</h1>
здесь и далее проверь опечатки в названиях классов и тексте

2022-12-06 07:50 UTC, babtshe commented on source/catalog.html
> +              <dd class="catalog__description-3-sub">700 ₽</dd>
стоит избегать цифр в названии классов, это не несёт никакой дополнительной информации.

2022-12-06 07:50 UTC, babtshe commented on source/form.html
> +              <input class="section-form__controls-input visually-hidden" type="checkbox" name="Дополнительные" checked>
см [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#b29)

2022-12-08 07:28 UTC, babtshe requested changes

2022-12-08 07:28 UTC, babtshe commented on source/catalog.html
> +        <a class="main-header__logo2" href="index.html"><img src="img/index/logo-txt.svg" alt="логотип"></a>
стоит избавиться от цифр в названии классов и придумать текстовое описание отличий. Если отличий нет, то отдельного названия элемент тоже не заслуживает

2022-12-08 07:28 UTC, babtshe commented on source/catalog.html
> +      <h1 class="catalog__titel">каталог продукции</h1>
title же здесь и далее по коду

2022-12-08 07:28 UTC, babtshe commented on source/catalog.html
> +      <a class="socials__link socials__link--telegramm" ref="#"></a>
проверь атрибуты ссылок

2022-12-08 07:28 UTC, babtshe commented on source/form.html
> +              <input class="section-form__controls-input visually-hidden" type="checkbox" value="питьевая вода"
см [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#b29)

2022-12-09 12:34 UTC, babtshe approved these changes

2022-12-09 12:35 UTC, merged