Коммит 17.12
htmlacademy-adaptive/2198955-cat-energy-27 pull request #3
Opened 2022-12-16 23:02 UTC by danikoff

2022-12-16 23:13 UTC, danikoff commented
При следующей правки уберу эроры , пустые scss файлы.

2022-12-18 09:17 UTC, babtshe requested changes
<img width="581" alt="image" src="https://user-images.githubusercontent.com/30229773/208289976-7e95f88a-04f9-45c3-a70b-b69a6fe3083f.png">
Для элементов отдельные файлы не нужны, только для блоков

Хорошо бы поправить опечатки в названиях классов во всём проекте. Если используются слова, которых нет в английском языке, не будет засчитан [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#b29).

2022-12-18 09:17 UTC, babtshe commented on .stylelintrc
> +    "at-rule-no-unknown": null
?

2022-12-18 09:17 UTC, babtshe commented on source/catalog.html
> +        <div class="main-nav__container visually-hidden">
а зачем скрывать навигацию в разметке? Если стили не прогрузились, что делать пользователю?

2022-12-18 09:17 UTC, babtshe commented on source/catalog.html
> +          <div><a class="button button-item" href="#">заказать</a></div>
зачем тут обёртка появилась?
Какая польза от дополнительного блока `button-item`?

2022-12-18 09:17 UTC, babtshe commented on source/catalog.html
> +      <h1 class="catalog__titel catalog__indent">Каталог продукции</h1>
Хорошо бы оставить только один из классов. Отдельный блок может быть элементом другого, но двумя элементами одного и того же блока не может.
❗️~~titel~~ title здесь и далее

2022-12-18 09:17 UTC, babtshe commented on source/catalog.html
> +      <p class="stock__desc stock__indent">
отдельный класс для расположения полезен только если ты двигаешь блок внутри другого блока. Вешать на несамостоятельный элемент класс только чтобы его расположить - бессмысленно.

Например, `class="catalog__item product"` имеет право на жизнь, а `class="catalog__item catalog__whatever"` - нет.

2022-12-18 09:17 UTC, babtshe commented on source/form.html
> +  <link rel="stylesheet" href="css/style.css">
было бы правильно подключить стили во всём проекте единообразно

2022-12-18 09:17 UTC, babtshe commented on source/form.html
> +      <fieldset class="select-program-catalog fieldsets-indent">
точно ли нужен отдельный блок на каждый раздел формы, при том что они выглядят похоже?

2022-12-18 09:17 UTC, babtshe commented on source/form.html
> +              <span class="section-form__lable-style">похудение</span>
какая польза от `style` в названии класса?

2022-12-18 09:17 UTC, babtshe commented on source/sass/blocks/adventages.scss
> +.adventages {
опечатка в названии блока по всему файлу

2022-12-18 09:17 UTC, babtshe commented on source/sass/blocks/adventages.scss
> +  font-family: "Oswald", sans-serif;
см [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#b10)
Значение шрифтов хорошо вынести в переменную - это позволит поменять шрифт во всём проекте в одном месте, то же касается и цветов

2022-12-18 09:17 UTC, babtshe commented on source/sass/blocks/catalog__show-more.scss
> +.catalog__show-more {
❗️

2022-12-18 09:17 UTC, babtshe commented on source/sass/blocks/main.scss
> +  // background-color: #000000;
❗️

2022-12-18 09:17 UTC, babtshe commented on source/sass/blocks/page__body.scss
> +  src: url("../../fonts/lato/Lato-Regular.woff2") format("woff2");
стоит перепроверить пути во всём проекте. Сейчас по такой ссылке 404 вместо шрифта
<img width="542" alt="image" src="https://user-images.githubusercontent.com/30229773/208290277-c351f91c-7f3e-4313-8301-a1be3556e7dc.png">

2022-12-18 09:17 UTC, babtshe commented on source/sass/blocks/section-form.scss
> +}
нужны ли тут отдельные элементы, если стили для всех одинаковые?

2022-12-18 09:17 UTC, babtshe commented on source/sass/blocks/section-form.scss
> +}
это добро должно жить в отдельных файлах, здесь и далее

2022-12-18 09:47 UTC, danikoff commented on source/catalog.html
> +        <div class="main-nav__container visually-hidden">
Забыл убрать, это я для удобства себе скрыл)

2022-12-18 09:53 UTC, danikoff commented on source/catalog.html
> +          <div><a class="button button-item" href="#">заказать</a></div>
Обертку забыл убрать, она для экспериментов, сложности были с флексом
От button-item никакой пользы

2022-12-20 10:44 UTC, danikoff commented on source/form.html
> +              <span class="section-form__lable-style">похудение</span>
Никакой

2022-12-23 10:47 UTC, babtshe requested changes
Стало значительно лучше, осталось поправить несколько небольших недочётов и избавится от предупреждений линтера.

2022-12-23 10:47 UTC, babtshe commented on source/form.html
> +              <span class="section-form__style--control">сахарозаменитель</span>
модификатор не используется без элемента/блока, который он модифицирует.

2022-12-23 10:47 UTC, babtshe commented on source/form.html
> +              <span class="section-form__style--control">питьевая вода</span>
какую полезную информацию несёт `style` в названии класса?

2022-12-23 10:47 UTC, babtshe commented on source/sass/blocks/button.scss
> +  font-family: var(--oswald);
переменным лучше давать абстрактные названия, без учёта текущего содержимого. Если со временем шрифт поменяется на какой-нибудь Arial, название переменной будет вводить в заблуждение. 
Будет полезно подумать в сторону назначения текущего начертания шрифта, например: основной/акцентный итд.

2022-12-23 10:47 UTC, babtshe commented on source/sass/blocks/catalog.scss
> +  color: #111111;
цвета тоже полезно вынести в переменные по аналогии со шрифтами. Это значительно упростит например включение новогодней темы на сайте.

2022-12-23 10:47 UTC, babtshe commented on source/sass/blocks/controls-input-indent.scss
> +.controls-input-indent {
похоже этот элемент не может использоваться самостоятельно и отдельного блока не заслуживает

2022-12-23 10:47 UTC, babtshe commented on source/sass/blocks/extra.scss
>  .extra__product-titel {
titel остался

2022-12-25 09:52 UTC, babtshe approved these changes

2022-12-25 09:52 UTC, merged